# Generated by Django 2.0.2 on 2020-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
